id: I55AA1224
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T18:31:23+00:00'
last_modified: '2022-06-08T03:01:19.836433+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3MS502
  title: འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེའི་རྣམ་པར་ཐར་པ་ཡོངས་སུ་བརྗོད་པའི་གཏམ་དུ་བྱ་བ་དད་པའི་སྒོ་འབྱེད་ཀཻ་ཏ་ཀའི་འཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    08B6:
      image_group_id: I3MS504
      title: ''
      total_pages: 418
      order: 1
      base_file: 08B6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
