id: I55AA1224
legacy_id: P005428
ocr_import_info:
  bdrc_scan_id: W3MS502
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T18:28:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:07:50.872310+00:00'
last_modified: 2022-09-04 01:08:06.582940
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3MS502
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3MS502
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེའི་རྣམ་པར་ཐར་པ་ཡོངས་སུ་བརྗོད་པའི་གཏམ་དུ་བྱ་བ་དད་པའི་སྒོ་འབྱེད་ཀཻ་ཏ་ཀའི་འཕྲེང་བ།
  author: བསེ་ཚང ༠༡་ངག་དབང་བཀྲ་ཤིས།
statistics:
  ocr_word_mean_confidence_index: 0.5861499315102878
  ocr_word_median_confidence_index: 0.5899999737739563
quality: null
bases:
  I3MS504:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3MS504
      total_pages: 418
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3MS504.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5861499315102878
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
