id: opecha:P005428
initial_creation_type: ocr
source_metadata:
  id: bdr:W3MS502
  title: འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེའི་རྣམ་པར་ཐར་པ་ཡོངས་སུ་བརྗོད་པའི་གཏམ་དུ་བྱ་བ་དད་པའི་སྒོ་འབྱེད་ཀཻ་ཏ་ཀའི་འཕྲེང་བ།
  volume: ''
  author: ''
